add export image function
YACS-RCOS/yacs-web pull request #53
Opened 2018-03-20 21:20 UTC by fakedestinyck

#51

2018-03-20 21:56 UTC, Bad-Science requested changes
Thanks! Requested changes. Please add a description to the PR as well :)

2018-03-20 21:56 UTC, Bad-Science commented on src/app/schedule-view/component.ts
> +@Component({
What's this?

2018-03-20 21:56 UTC, Bad-Science commented on src/app/schedule-view/component.ts
> +      var node = document.getElementById('schedule-container');
The conventional way to get DOM elements in Angular is using the ViewChild API. see: https://angular.io/api/core/ViewChild

2018-03-20 21:56 UTC, Bad-Science commented on src/app/schedule-view/component.html
> +      <!-- <button class="schedule-button" (click) = "showExport()">Export as ...</button> -->
Please remove commented code

2018-03-20 21:56 UTC, Bad-Science commented on src/app/schedule-view/component.html
> +            Export as ...
Can we make this say "share", and then make the drop down item say "download image"

2018-03-30 01:41 UTC, fakedestinyck commented
@Bad-Science  Updated

2018-03-30 18:24 UTC, Bad-Science commented
@fakedestinyck Thanks so much! This looks great, I'll merge it shortly! Would you mind just posting a screenshot of the button, and one of the downloaded schedule images in this thread for reference?

Thanks again!

2018-03-30 18:24 UTC, Bad-Science approved these changes

2018-03-30 19:31 UTC, fakedestinyck commented
Here is the button:
<img width="633" alt="screen shot 2018-03-30 at 15 28 57" src="https://user-images.githubusercontent.com/16526801/38150985-69d69c26-342f-11e8-9c4a-a2056f9fc1f3.png">
And the downloaded schedule image:
![myschedules](https://user-images.githubusercontent.com/16526801/38150996-761f0694-342f-11e8-9701-52f9716487f1.png)

2018-03-30 19:45 UTC, merged