Notice Bar Front End
YACS-RCOS/yacs-web pull request #60
Opened 2018-03-24 20:44 UTC by milnej

This pull request addresses the notice bar issue:
https://github.com/YACS-RCOS/yacs/issues/232

When there is a notice to be displayed to the user it will be displayed under the header bar. This has been implemented through ng-bootstrap alerts. Once a notice is dismissed through the x button on the far right, the next notice in the queue will display. 

To use this feature the API for the notice bar must be implemented into the back end. This PR satisfies the front end.

2018-03-24 20:57 UTC, Bad-Science requested changes
Thanks for the PR! Great work! Requested one minor fix, then good to go!

2018-03-24 20:57 UTC, Bad-Science commented on src/app/services/yacs.service.ts
> +  protected baseUrl = 'https://yacs.cs.rpi.edu/api/v5';
Pls change this back :)

2018-03-25 18:31 UTC, milnej commented
I have made the requested fix!

2018-03-25 19:50 UTC, Bad-Science approved these changes

2018-03-25 19:50 UTC, Bad-Science commented
Looks good! Thanks @milnej !

2018-03-25 19:50 UTC, merged