Improve appearance of scheduling page
YACS-RCOS/yacs-web pull request #80
Opened 2018-06-22 19:05 UTC by sjhuang26

* make schedule buttons consistent with rest of UI
* refactor schedule-menu to use flexbox
* if you hover over an overflowing schedule event, a scrollbar will appear
![image](https://user-images.githubusercontent.com/29558846/41794202-9ae7be14-762c-11e8-93d2-13fcfce6fdd2.png)

2018-06-22 19:46 UTC, Bad-Science commented
Thanks for the PR @sjhuang26 !

I think these buttons are an improvement and I like using flexbox here.

I also like being able to handle the overflowing schedule events, but rather than having scrollbars appear, could we make it so they simply expand as necessary when you hover over them? I think that would be a little cleaner.

2018-06-22 19:46 UTC, Bad-Science requested changes
Thanks for the PR! See above comments for request changes

2018-06-23 15:17 UTC, sjhuang26 commented
Requested changes have been made.

2018-06-24 21:02 UTC, Bad-Science commented on src/app/schedule-view/schedule-event/component.ts
> +        return this.hover ? 'auto' : this.normalHeight + 'px';
Great thanks! Looks good, can we just add (return) type annotations to these functions, and use two-space indentation @sjhuang26 ? Then I will merge this.

2018-06-25 01:29 UTC, sjhuang26 commented
More requested changes have been made.

2018-06-25 03:05 UTC, Bad-Science commented on src/app/schedule-view/schedule-event/component.ts
> +  getHeight(): number {
this returns a string not a number, right?

2018-06-25 18:05 UTC, Bad-Science approved these changes

2018-06-25 18:05 UTC, Bad-Science commented
LGTM, thanks @sjhuang26 !

2018-07-12 01:44 UTC, merged